### ISSUE TITLE
Could you give me some tips?

### ISSUE THREAD

**Issue by CrazyWolf13** [Marcusronney/dashboard_cisco_switch_grafana#1]
Hi

This dashboard looks really awesome!

I'm currently looking into building my own dashboard for my cisco sg300 switch.
As far as I can see, you used some sort of zabbix instance to get the data?
Could you elaborate a bit on that? I'm not personally a zabbix user.

I looked into the following way: SNMP on Switch <-Telegraf->InfluxDB <- Grafana
But I'm curious, what role zabbix played in this setup :)

Thanks for some insights, and that is really a awesome dashboard! :)

**Comment by Marcusronney** [comment]
Good morning, thanks for the feedback.

I used Zabbix to collect data. Zabbix's role is to connect to the switch's SNMP and collect data. Within Zabbix, the device is registered and the information is collected. This information is processed by a template. This template is configured to collect and display the Switch's metrics. Within Zabbix, you will have all the metrics, history, and alerts. Grafana is used only to display a dashboard of the data collected from Zabbix.

SNMP Switch > Zabbix > Grafana

Cisco devices have many OIDs in common. You can use any standard Cisco template that will work.

I will soon post the Zabbix Deployment from scratch on Rocky Linux.

**Comment by CrazyWolf13** [comment]
Good evening!
Thanks for the detailed Feedback :)

That seems like a neat way, I'll definitely have to further look into this!

Sounds awesome! 
And thanks again!
